version: '3.8'

services:
  # Service Database MySQL
  db:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      # UBAH DISINI: Mengambil nilai dari file .env
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # Service Aplikasi Node.js
  app_service:
    build: ./app
    container_name: node_app
    ports:
      - "${APP_PORT}:3000"  # Mengambil port dari .env (3000)
    environment:
      # UBAH DISINI: Mengambil nilai dari file .env
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SESSION_SECRET: ${SESSION_SECRET} # Tambahan untuk session
    depends_on:
      - db
    networks:
      - app_network

  # Service Web Server Nginx (Port 80)
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: